name: BabaManda
favicon: null
layout_spectrum: 0.50179
typography_spectrum: 0.49263
title: BabaManda
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090c09'
    - '#ffffff'
    - '#46565e'
    - '#9ea8a6'
    - '#dadf90'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
